Chana/marker sets
edipoarg/components pull request #4
Opened 2024-04-02 16:14 UTC by juanigaray

2024-04-02 20:02 UTC, xaiki requested changes
API seems weird to me.

2024-04-02 20:02 UTC, xaiki commented on lib/components/Map/Map.tsx
> +        style={{ width: "20px", height: "20px" }}
shouldn't this style be settable somehow ?

2024-04-02 20:02 UTC, xaiki commented on lib/components/Map/Map.tsx
> +      )}
wrap each poiSet into it's element, even if it's a NOP
so that it can be debugged from the react componenent tree.

2024-04-02 20:02 UTC, xaiki commented on lib/components/Map/Map.tsx
> +      )}
this API DOES require to either use defaultMarker or to import Marker in my calling component, the point of all this is to abstract away from the reactmap-gl API, please give a way to define DefaultMarker (and maybe, use it here) that would not requiere using react-mapgl/Marker

also, the naming is confusing, is Marker my marker, is it React-map-gl one's ?

2024-04-02 21:14 UTC, juanigaray commented on lib/components/Map/Map.tsx
> +  Marker?: (poi: T) => JSX.Element;
It's a HOC! How does it look weird?

2024-04-02 21:16 UTC, juanigaray commented on lib/components/Map/Map.tsx
> +} => {
done

2024-04-02 21:26 UTC, juanigaray commented on lib/components/Map/Map.tsx
> +    "key" in poi
Typescript has no runtime representation like other languages like Java do. All type checks are done at compile time, except for those that are part of the Javascript specification (like `typeof`). 

This is, in my interpretation, because of the [Typescript design goals 3, 4, 7 and 9](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals). 

There are other more sophisticated solutions like [Zod](https://zod.dev/?id=introduction) which combine runtime checks and the Typescript type system, but I don't believe that the tradeoff of adding a library like that is worth it at the moment.

2024-04-02 21:27 UTC, juanigaray commented on lib/components/Map/Map.tsx
> +        src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimagensemoldes.com.br%2Fwp-content%2Fuploads%2F2020%2F08%2FFoto-de-Pin-PNG.png&f=1&nofb=1&ipt=f73aa1ce4b802d9e34ec1230736689ea
Sure!

2024-04-02 21:35 UTC, juanigaray commented on lib/components/Map/Map.tsx
> +        style={{ width: "20px", height: "20px" }}
What was your intention when writing this code? Should this style be settable?

I don't see the need for a default marker. I'd make the poi-to-marker function non-optional and let the component break when misused. I think this would make our code clearer.

Ultimately, this style is settable by the user if they just pass their own poi-to-marker function. Customizability is provided by the current API.

2024-04-02 21:37 UTC, juanigaray commented on lib/components/Map/Map.tsx
> +      )}
- You're absolutely right about this API still needing the library Marker, I'll fix that.
- Marker is the Marker in the component API, as that's the name we're exposing to the user.

I'll let you know when I've pushed a new version with the fix

2024-04-02 21:39 UTC, juanigaray commented on lib/components/Map/Map.tsx
> +import { Marker } from "react-map-gl";
Fixed <3

2024-04-03 15:28 UTC, juanigaray commented on lib/components/Map/Map.tsx
> +        src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimagensemoldes.com.br%2Fwp-content%2Fuploads%2F2020%2F08%2FFoto-de-Pin-PNG.png&f=1&nofb=1&ipt=f73aa1ce4b802d9e34ec1230736689ea
done

2024-04-05 20:12 UTC, xaiki commented on lib/components/Map/Map.tsx
> +  Marker?: (poi: T) => JSX.Element;
maybe it should be called MarkerComponent ?

2024-04-05 20:13 UTC, xaiki commented on lib/components/Map/Map.tsx
> +    "key" in poi
yeah no, ok, we probably have to keep 'something like this'

2024-04-05 20:13 UTC, xaiki commented on lib/components/Map/Map.tsx
> +    "key" in poi
or use the evil m2cms code to generate type checking ? no no just kidding.

2024-04-05 20:14 UTC, xaiki commented on lib/components/Map/Map.tsx
> +      )}
<3

2024-04-05 20:14 UTC, xaiki commented on lib/components/Map/Map.tsx
> +        style={{ width: "20px", height: "20px" }}
this is actually discussed in the next comment.

2024-04-05 20:17 UTC, xaiki commented on lib/components/Map/Map.tsx
> +      )}
PoiMarker lgtm

2024-04-05 20:18 UTC, xaiki reviewed
is the new API ready ?

2024-04-08 13:11 UTC, juanigaray commented on lib/components/Map/Map.tsx
> +  Marker?: (poi: T) => JSX.Element;
That'd be redundant and noisy to me, like calling a function that fetches data `fetchDataFunction` or calling a class that represents a patient `PatientClass`. 

I think it's important to ask these questions:

- How does this field look weird?
- How does weirdness affect code quality?
- Why do you think it should be called that?

2024-04-08 18:12 UTC, juanigaray commented on lib/components/Map/Map.tsx
> +        style={{ width: "20px", height: "20px" }}
Is this resolved?

2024-04-08 18:12 UTC, juanigaray commented on lib/components/Map/Map.tsx
> +      )}
Is this resolved? Please mark resolved discussions as such so I can focus on unresolved ones

2024-04-11 14:27 UTC, xaiki commented on lib/components/Map/Map.tsx
> +  Marker?: (poi: T) => JSX.Element;
simply because i do not expect a component to be part of a struct (or interface in this case), but if you feel it's alright we're going your way.

2024-04-11 14:44 UTC, xaiki approved these changes
I have a few NITs, but if they seem far fetched to you, this can go-in as-is.

2024-04-11 14:44 UTC, xaiki commented on lib/components/Map/Marker.tsx
> +    "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimagensemoldes.com.br%2Fwp-content%2Fuploads%2F2020%2F08%2FFoto-de-Pin-PNG.png&f=1&nofb=1&ipt=f73aa1ce4b802d9e34ec1230736689ea2f6cf1d6
does it make sense to have it exported from the file ?

2024-04-11 14:44 UTC, xaiki commented on lib/components/Map/Marker.tsx
> +      longitude={Number(poi.coords.longitude)}
why the Number() guard ?
shouldn't number be enforced by the type ?
also (NIT) i prefer {...poi.coords}

2024-04-11 14:44 UTC, xaiki commented on lib/components/Map/Marker.tsx
> +  <MapGlMarker latitude={coords.latitude} longitude={coords.longitude}>
here you don't do Number() guard, 
NIT: i prefer `{...coords}`

2024-04-11 17:32 UTC, juanigaray commented on lib/components/Map/Marker.tsx
> +    "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimagensemoldes.com.br%2Fwp-content%2Fuploads%2F2020%2F08%2FFoto-de-Pin-PNG.png&f=1&nofb=1&ipt=f73aa1ce4b802d9e34ec1230736689ea2f6cf1d6
Exported from this file? Where else would it be used?

Let's discuss this further in an issue

2024-04-11 17:35 UTC, merged